name: trigger postgres build on push
run-name: ${{ github.actor }} triggered build 🚀
on:
  push:
    branches:
      - main
jobs:
  call-build:
    uses: ./.github/workflows/build-postgres.yaml
    with:
      tag: REL_13_15 # DO NOT CHANGE THIS LINE. this default value will be overridden automatically
